[package]
name = "async_futex-rs"
version = "0.1.0"
authors = ["Isitha Subasinghe <isubasinghe@student.unimelb.edu.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-queue = "0.3.2"
